name: screen_secure
description: A Flutter plugin for screen security features including screenshot and screen recording protection across Android and iOS platforms.
version: 1.0.2
homepage: https://github.com/shariaralphabyte/screen_secure
repository: https://github.com/shariaralphabyte/screen_secure
issue_tracker: https://github.com/shariaralphabyte/screen_secure/issues

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.shariar99.screen_secure
        pluginClass: ScreenSecurePlugin
      ios:
        pluginClass: ScreenSecurePlugin

topics:
  - security
  - screenshot
  - screen-recording
  - privacy
  - protection