name: screen_secure
description: A Flutter plugin for screen security features including screenshot and screen recording protection.
version: 1.0.0
homepage: https://github.com/yourusername/screen_secure
repository: https://github.com/yourusername/screen_secure
issue_tracker: https://github.com/yourusername/screen_secure/issues
documentation: https://pub.dev/documentation/screen_secure/latest/

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.shariar99.screen_secure
        pluginClass: ScreenSecurePlugin
      ios:
        pluginClass: ScreenSecurePlugin

topics:
  - security
  - screenshot
  - screen-recording
  - privacy
  - protection